import math
import string
import hashlib

def calculate_entropy(password):
    charset = 0

    if any(c.islower() for c in password):
        charset += 26

    if any(c.isupper() for c in password):
        charset += 26

    if any(c.isdigit() for c in password):
        charset += 10

    if any(c in string.punctuation for c in password):
        charset += 32

    if charset == 0:
        return 0

    entropy = len(password) * math.log2(charset)
    return round(entropy, 2)


def password_strength(password):
    score = 0

    if len(password) >= 8:
        score += 20

    if len(password) >= 12:
        score += 20

    if any(c.isupper() for c in password):
        score += 20

    if any(c.islower() for c in password):
        score += 10

    if any(c.isdigit() for c in password):
        score += 15

    if any(c in string.punctuation for c in password):
        score += 15

    if score >= 80:
        return score, "Strong"

    elif score >= 50:
        return score, "Medium"

    else:
        return score, "Weak"
def estimate_crack_time(entropy):
    guesses_per_second = 1_000_000_000

    seconds = (2 ** entropy) / guesses_per_second

    if seconds < 60:
        return f"{seconds:.2f} seconds"

    elif seconds < 3600:
        return f"{seconds/60:.2f} minutes"

    elif seconds < 86400:
        return f"{seconds/3600:.2f} hours"

    elif seconds < 31536000:
        return f"{seconds/86400:.2f} days"

    else:
        return f"{seconds/31536000:.2f} years"
def is_common_password(password):
    with open("common_passwords.txt", "r") as file:
        common = [line.strip() for line in file]

    return password.lower() in common
def has_repeated_characters(password):
    return len(set(password)) <= len(password) / 2


def has_sequential_pattern(password):
    sequences = [
        "123456789",
        "abcdefghijklmnopqrstuvwxyz",
        "qwertyuiop",
        "asdfghjkl"
    ]

    password = password.lower()

    for seq in sequences:
        for i in range(len(seq) - 3):
            pattern = seq[i:i+4]
            if pattern in password:
                return True

    return False

import random
import string

def generate_password(length=16):
    chars = string.ascii_letters + string.digits + string.punctuation
    return ''.join(random.choice(chars) for _ in range(length))


from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

def generate_pdf_report(
        score,
        strength,
        entropy,
        crack_time,
        filename="Password_Security_Report.pdf"
):
    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph("PASSWORD SECURITY REPORT", styles['Title'])
    )

    content.append(Spacer(1, 12))

    content.append(
        Paragraph(f"Strength Score: {score}/100", styles['Normal'])
    )

    content.append(
        Paragraph(f"Password Rating: {strength}", styles['Normal'])
    )

    content.append(
        Paragraph(f"Entropy: {entropy:.2f} bits", styles['Normal'])
    )

    content.append(
        Paragraph(f"Estimated Crack Time: {crack_time}", styles['Normal'])
    )

    content.append(Spacer(1, 20))

    content.append(
        Paragraph("Generated by Smart Password Strength Analyzer", styles['Italic'])
    )

    doc.build(content)

    return filename


def generate_hashes(password):

    hashes = {
        "MD5": hashlib.md5(password.encode()).hexdigest(),
        "SHA1": hashlib.sha1(password.encode()).hexdigest(),
        "SHA256": hashlib.sha256(password.encode()).hexdigest(),
        "SHA512": hashlib.sha512(password.encode()).hexdigest()
    }

    return hashes